# Generated by Django 3.0.6 on 2020-05-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combatnutrion',
            options={'verbose_name': 'Боепитание', 'verbose_name_plural': 'Боепитание'},
        ),
        migrations.AlterField(
            model_name='combatnutrion',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='combatnutrion',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='armor',
            field=models.FloatField(null=True, verbose_name='Толщина брони'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='crew',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Экипаж'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='curb_weight',
            field=models.FloatField(null=True, verbose_name='Снаряженная масса'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='height',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='length',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='passengers',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Пассажиры'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='power',
            field=models.FloatField(null=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='speed',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Ширина'),
        ),
    ]
