# Generated by Django 3.0.6 on 2020-05-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200509_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatnutrion',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
