# Generated by Django 3.0.6 on 2020-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200509_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatnutrion',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Вес'),
        ),
    ]
